In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("../data/processed/online_retail_clean.csv")

In [4]:
df.head()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  object
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  int64
 7   Country      392692 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 24.0+ MB

(392692, 8)

In [5]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [8]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [9]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [10]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M")

df[["InvoiceDate", "InvoiceMonth"]].head()

          InvoiceDate InvoiceMonth
0 2010-12-01 08:26:00      2010-12
1 2010-12-01 08:26:00      2010-12
2 2010-12-01 08:26:00      2010-12
3 2010-12-01 08:26:00      2010-12
4 2010-12-01 08:26:00      2010-12

In [11]:
df["InvoiceYear"] = df["InvoiceDate"].dt.year

In [12]:
df["InvoiceDay"] = df["InvoiceDate"].dt.day_name()

In [13]:
df["InvoiceHour"] = df["InvoiceDate"].dt.hour

In [14]:
df["IsWeekend"] = df["InvoiceDate"].dt.dayofweek >= 5
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth,InvoiceYear,InvoiceDay,InvoiceHour,IsWeekend
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010-12,2010,Wednesday,8,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,2010,Wednesday,8,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010-12,2010,Wednesday,8,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,2010,Wednesday,8,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,2010,Wednesday,8,False

In [15]:
df["Revenue"].sum()

np.float64(8887208.894000001)

In [16]:
df["CustomerID"].nunique()

4338

In [17]:
df["InvoiceNo"].nunique()

18532

In [18]:
df["StockCode"].nunique()

3665

In [19]:
total_revenue = df["Revenue"].sum()

total_orders = df["InvoiceNo"].nunique()

AOV = total_revenue / total_orders

print(AOV)

479.56016047917126

In [20]:
df[df["Revenue"] <= 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, Revenue, InvoiceMonth, InvoiceYear, InvoiceDay, InvoiceHour, IsWeekend]
Index: []

In [21]:
(df["Quantity"] <= 0).sum()

np.int64(0)

In [22]:
(df["UnitPrice"] <= 0).sum()

np.int64(0)

In [23]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("Customers:", df["CustomerID"].nunique())

print("Orders:", df["InvoiceNo"].nunique())

print("Revenue:", round(df["Revenue"].sum(),2))

Rows: 392692
Columns: 14
Customers: 4338
Orders: 18532
Revenue: 8887208.89

In [24]:
df.to_csv("../data/processed/online_retail_final.csv", index=False)

# Feature Engineering Summary

### New Features Created

- Revenue
- InvoiceMonth
- InvoiceYear
- InvoiceDay
- InvoiceHour
- MonthName
- IsWeekend

### Data Validation

- No Missing Values
- No Duplicate Records
- No Negative Quantity
- No Invalid Prices
- Revenue Successfully Calculated

Dataset is now ready for Exploratory Data Analysis (EDA).